# https://travis-ci.org/kecnry/mpltracker

language: python

addons:
  apt:
    sources:
    # add PPAs with more up-to-date toolchains
    - ubuntu-toolchain-r-test

dist: trusty

env:
    global:
        # Set defaults to avoid repeating in most cases
        - CONDA_DEPENDENCIES='matplotlib'
        - PIP_DEPENDENCIES='nose matplotlib'

matrix:

    # Don't wait for allowed failures
    fast_finish: true

    include:

        # Try with lowest supported matplotlib (only with python 2.7)
        - os: linux
          env: PYTHON_VERSION=2.7 MATPLOTLIB_VERSION=1.5'

        - os: osx
          env: PYTHON_VERSION=2.7 MATPLOTLIB_VERSION=1.5'

        # Try with stable versions of matplotlib
        - os: linux
          env: PYTHON_VERSION=2.7 MATPLOTLIB_VERSION=stable'

        - os: linux
          env: PYTHON_VERSION=3.6 MATPLOTLIB_VERSION=stable'

        - os: osx
          env: PYTHON_VERSION=2.7 MATPLOTLIB_VERSION=stable'

        - os: osx
          env: PYTHON_VERSION=3.6 MATPLOTLIB_VERSION=stable'

        # Try with dev version of numpy (only with python 3.6)
        - os: linux
          env: PYTHON_VERSION=3.6 MATPLOTLIB_VERSION=dev'

        - os: osx
          env: PYTHON_VERSION=3.6 MATPLOTLIB_VERSION=dev'

    allow_failures:
      - env: NUMPY_VERSION=dev

before_install:
    - rvm get head
    - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then
        brew update;
      fi;

install:
    - git clone git://github.com/astropy/ci-helpers.git
    - source ci-helpers/travis/setup_conda.sh
    - python setup.py build
    - python setup.py install --user

script:
    - nosetests -v -s -d -w tests/;
